import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { ArrowLeft, Sparkles } from "lucide-react";
import { useLocation } from "wouter";

export default function Terms() {
  const [, navigate] = useLocation();

  return (
    <div className="min-h-screen bg-background">
      <header className="border-b border-border bg-card/50">
        <div className="max-w-4xl mx-auto px-4 py-4 flex items-center justify-between">
          <div className="flex items-center gap-2">
            <div className="w-8 h-8 rounded-lg bg-primary flex items-center justify-center">
              <Sparkles className="w-5 h-5 text-primary-foreground" />
            </div>
            <span className="font-semibold text-lg">Skool Launch Plan Creator</span>
          </div>
          <Button variant="ghost" onClick={() => navigate("/")} data-testid="button-back-home">
            <ArrowLeft className="mr-2 h-4 w-4" />
            Back to Home
          </Button>
        </div>
      </header>

      <main className="max-w-3xl mx-auto px-4 py-12">
        <Card>
          <CardHeader>
            <CardTitle className="text-2xl">Terms of Service</CardTitle>
          </CardHeader>
          <CardContent className="prose prose-sm max-w-none dark:prose-invert">
            <p className="text-muted-foreground">Last updated: February 2025</p>

            <h2 className="text-lg font-semibold mt-6 mb-3">1. Acceptance of Terms</h2>
            <p>
              By using the Skool Launch Plan Creator ("the Tool"), you agree to these Terms of Service. 
              If you don't agree, please don't use the Tool.
            </p>

            <h2 className="text-lg font-semibold mt-6 mb-3">2. What This Tool Does</h2>
            <p>
              The Skool Launch Plan Creator generates educational content to help you plan and launch a 
              Skool community or course. The plans are generated using AI and are meant to serve as a 
              starting point for your own research and planning.
            </p>

            <h2 className="text-lg font-semibold mt-6 mb-3">3. Educational Purpose Only</h2>
            <p>
              <strong>Important:</strong> All content generated by this Tool is for educational and 
              informational purposes only. The Tool does not provide:
            </p>
            <ul className="list-disc pl-6 space-y-2">
              <li>Financial advice or income guarantees</li>
              <li>Legal advice</li>
              <li>Medical advice</li>
              <li>Professional business consulting</li>
            </ul>
            <p>
              Any business decisions you make based on the generated plans are your own responsibility. 
              Results vary, and there is no guarantee of success or income.
            </p>

            <h2 className="text-lg font-semibold mt-6 mb-3">4. No Income Guarantees</h2>
            <p>
              We make no representations or guarantees about your potential earnings or business success. 
              Building a successful online community or course requires significant effort, and results 
              depend on many factors outside our control, including:
            </p>
            <ul className="list-disc pl-6 space-y-2">
              <li>Your effort and consistency</li>
              <li>Market conditions</li>
              <li>Your niche and audience</li>
              <li>Your existing skills and network</li>
              <li>Many other variables</li>
            </ul>

            <h2 className="text-lg font-semibold mt-6 mb-3">5. AI-Generated Content</h2>
            <p>
              The plans are generated using artificial intelligence. While we strive for accuracy and 
              helpfulness, AI-generated content may:
            </p>
            <ul className="list-disc pl-6 space-y-2">
              <li>Contain inaccuracies or outdated information</li>
              <li>Not be suitable for every situation</li>
              <li>Require your own review and adaptation</li>
            </ul>
            <p>
              Always use your own judgment and do additional research before acting on any suggestions.
            </p>

            <h2 className="text-lg font-semibold mt-6 mb-3">6. Rate Limits</h2>
            <p>
              To ensure fair access for everyone, we limit usage to:
            </p>
            <ul className="list-disc pl-6 space-y-2">
              <li>3 plan generations per user per day</li>
              <li>100 total generations globally per day</li>
            </ul>
            <p>
              These limits reset daily. Attempting to circumvent rate limits may result in access restrictions.
            </p>

            <h2 className="text-lg font-semibold mt-6 mb-3">7. Acceptable Use</h2>
            <p>You agree not to use this Tool to:</p>
            <ul className="list-disc pl-6 space-y-2">
              <li>Generate content that violates any laws</li>
              <li>Create misleading or fraudulent business schemes</li>
              <li>Harm, harass, or deceive others</li>
              <li>Circumvent rate limits or abuse the service</li>
            </ul>

            <h2 className="text-lg font-semibold mt-6 mb-3">8. Affiliate Disclosure</h2>
            <p>
              This Tool contains affiliate links to Skool. If you sign up for Skool through our links, 
              we may earn a commission at no additional cost to you. This does not affect the quality 
              or objectivity of the plans we generate.
            </p>

            <h2 className="text-lg font-semibold mt-6 mb-3">9. Limitation of Liability</h2>
            <p>
              THE TOOL IS PROVIDED "AS IS" WITHOUT WARRANTIES OF ANY KIND. WE ARE NOT LIABLE FOR ANY 
              DAMAGES ARISING FROM YOUR USE OF THE TOOL OR THE PLANS IT GENERATES. USE AT YOUR OWN RISK.
            </p>

            <h2 className="text-lg font-semibold mt-6 mb-3">10. Changes to Terms</h2>
            <p>
              We may update these terms from time to time. Continued use of the Tool after changes 
              constitutes acceptance of the new terms.
            </p>

            <h2 className="text-lg font-semibold mt-6 mb-3">11. Contact</h2>
            <p>
              For questions about these terms, please visit{" "}
              <a href="https://skoolprep.com" target="_blank" rel="noopener noreferrer" className="text-primary underline">
                SkoolPrep.com
              </a>.
            </p>
          </CardContent>
        </Card>
      </main>

      <footer className="border-t border-border mt-16 py-8 text-center text-sm text-muted-foreground">
        <p>
          Made with care by{" "}
          <a 
            href="https://skoolprep.com" 
            target="_blank" 
            rel="noopener noreferrer" 
            className="underline hover:text-foreground"
          >
            Skool Prep
          </a>
        </p>
      </footer>
    </div>
  );
}
